"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"
"I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT", "I LOVE JAVASCRIPT"


// 3.  Самое длинное имя в списке
// Отправляем функции три аргумента с разными именами
// Функция возвращает максимально длинное имя
// max_name('Alex', 'George', 'Michael')
console.log(`Задание 1 (самое длинное имя)`);

function max_name(name_1, name_2, name_3) {
    let max_name = name_1;
    if (name_2.length > max_name.length) {
        max_name = name_2;
    }
        if (name_3.length > max_name.length) {
        max_name = name_3;
    }
    return max_name;
  }
console.log( max_name('Alex', 'George', 'Michael'));
  
//  5. Создать функцию которая делает пропорции не в   зависимости от каких  либо цифр
console.log(`Задание 2 (пропорция)`);

let pr1 = +prompt(`Number!`).trim()
let pr2 = +prompt(`Number for proportion!`).trim()

function proportion(a, b) {
    a = pr1;
    b = pr2;
    if(a >= b) {
        console.log((b * 100) / a + "%");
    } else {
        console.log(`Error`);
    }
}
proportion();


// Создать цикл который будет выводить цифры фибоначчи и должно остановиться на той цифре которую напишите в промпте 
console.log("Задание 3 (фибоначчи)");

let pr = +prompt("Число, на котором нужно остановиться");
let f = [0, 1];

for(let i = 2; i < pr; i++) {
    f.push(f[f.length - 1] + f[f.length - 2]);
}


console.log(f);